services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
  db:
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=v50-tier3-team20
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  node_modules:
  db_data: